KIP-24: Improving KNC Liquidity and Pair Diversity
KyberNetwork/KIPs pull request #61
Opened 2023-06-20 04:15 UTC by ShaneKyber

We propose to further improve liquidity for KNC on KyberSwap as well as increase the type of tokens paired with KNC. 

A small portion of KNC from the KyberDAO ecosystem fund would be allocated to improving KNC liquidity, initially focusing on Ethereum, Polygon, Arbitrum, Optimism, Avalanche, and BNB Chain.

KyberDAO will vote for its preferred chains (and suggested KNC-paired pools) that would receive priority for the funds, based on a list highlighted in this proposal. For this KIP proposal, 100,000 KNC would be allocated for liquidity enhancement for each KNC pair selected as part of the winning vote.

2023-06-20 04:44 UTC, nktrong approved these changes

2023-06-20 07:50 UTC, tranvictor approved these changes

2023-06-26 04:47 UTC, manhlx3006 requested changes
Requested to change start and end date:

start_timestamp: 1687849200 (Tuesday, June 27, 2023 2:00:00 PM GMT+07:00)
end_timestamp: 1688454000 (Tuesday, July 4, 2023 2:00:00 PM GMT+07:00)

2023-06-26 07:21 UTC, manhlx3006 approved these changes

2023-06-26 07:21 UTC, merged